### ISSUE TITLE
Pose Templates (포즈 사전 정의) 기능 구현 방식에 대한 논의

### ISSUE THREAD

**Issue by Jeongah-Shin** [FollowMe-Beyond/followme-android#4]
**포즈 사전 정의 기능을 구현함에 있어서 Anko와 Canvas 중 어떤 방식을 채택해야 할지 고민입니다🤔**

**Canvas**
>안드로이드 뷰나 애니메이션을 구현함에 있어서 옛날 부터 자주 사용 되어왔던 방식입니다.

**Anko**
> Android KTXs (Kotlin Extensions)이 출시된 이후 나온 방식이며, 우리가 참고하고 있는 PoseEstimationForMobile 또한 실시간으로 View를 그려주는 과정에서 Anko 방식을 사용하고 있습니다.

**참고 링크**
- [Anko-Layouts](https://github.com/Kotlin/anko/wiki/Anko-Layouts)
- [Canvas](https://developer.android.com/reference/android/graphics/Canvas)

**Comment by Jeongah-Shin** [comment]
@YongGeunLee 

Zeplin을 통해 멘션드렸던 Pose Templates (포즈 사전 정의) 탭과 관련한 이슈입니다 🙂

**Comment by YongGeunLee** [comment]
Anko 로 구현함에 있어서 정아님의 불편함이 많으신가요? Canvas 는 익숙하실꺼 같은데?
둘다 상관없으시다고 하면 저는 anko가 좋을것 같습니다
어떻게 생각하시나요?

**Comment by Jeongah-Shin** [comment]
@YongGeunLee 의견 감사합니다🙂

- Canvas가 확실히 더 익숙합니다! 오늘 귀가 후에 Anko 공식 wiki 읽어보면서 공부해봤는데, 조금 생소하지만 알아두면 확실히 좋을 것 같아요~ 

- 용근님 의견 주신대로 일단 Anko로 작업 시작하겠습니다. 단, Learning curve 때문에 작업이 지연되는 상황이 발생한다면 차선책으로 Canvas 구현을 생각 해놓을게요🙏

- 부가적으로 PoseEstimationForMobile 저장소를 다시 확인해봤는데, 정확히는 Anko-Layout을 사용했다기 보다는 방식을 차용했다고 보는게 맞을 것 같습니다. 하지만 방식을 통일하면 코드 재사용성을 고려했을 때도 훨씬 좋을 것으로 생각됩니다. 

자세한 사항은 다음 오프라인 미팅에서 더 설명드릴게요😉
